todo/config/routes.rb
Rails.application.routes.draw do
  
  # sets views/listings/index.html.erb as the root of the website
  root 'listings#index'
  
  # create all the routes neeeded for listings (C.R.U.D.)
  resources :listings

end

todo/app/models/listing.rb
class Listing < ActiveRecord::Base
  # checks to see if there is a description value present in the description field when the form is submitted
  # this validation will show a error is the description filed does not have a value prestent
  # this will not allow a blank description field to be submitted
  validates_presence_of :description
end

todo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

todo/app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  
  # listings#index, index Action root(/)(/listings)
  def index
    # list all the current values in the list on the root page
    @listings = Listing.all
  end
  
  # listings#new, new Action (/listings/new)
  def new
    # allow user to create a new todo item
    @listing = Listing.new
  end
  
  # listings#create, create Action (/listings)  
  def create
    # enables the user to create a todo item to be stored on the root page
    @listing = Listing.new(listing_params)
    # checks if the new todo item that was created saves
    # if the new todo saves 
    if @listing.save
      # then it will redirect you back to the root page with the new todo item added to the list
      redirect_to listings_path
    else
      # else (does not save) it will render the new Action again
      render 'new'
    end
  end
  
  # listings#edit, deit Action (/listings/:id/edit)
  def edit
    # this allows the user to edit an existing todo item
    # this is done by first finding the the todo items listing params :id
    @listing = Listing.find(params[:id])
  end
  
  
  def update
    # this gets the todo items listing params :id
    @listing = Listing.find(params[:id])
    # if todo listing item updates
    if @listing.update(listing_params)
      # them it will redirect you to the root page along with the updated todo list item
      redirect_to listings_path
    else
      # else (does not update) it will render the edit Action again
      render 'edit'
    end
  end
  
  # listings#show, show Action (/listings/:id)
  def show
    # this gets the todo items listing params :id
    @listing = Listing.find(params[:id])
  end
  
  # listings#destroy, destroy Action (/listings/:id)
  def destroy
    # gets the todo items listing params :id
    @listing = Listing.find(params[:id])
    # destroys the current listing
    @listing.destroy
    
    # redirects you back to the (root) index page
    redirect_to listings_path
  end
  
  # defining listing_params for this classes use only
  private
    def listing_params
      # requires the top level listings key and then allows the description key value to be passed in
      params.require(:listing).permit(:description)
    end
end

todo/app/helpers/application_helper.rb
module ApplicationHelper
end

todo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

todo/app/views/listings/_form.html.erb
<% if obj.errors.any? %>
  <h2>There was an error in your submission</h2>
  <!-- This would be the standard for going through multiple error messages -->
  <ul>
    <!-- this would iterate over muliple errer messages but in this case it would be just one -->
    <% obj.errors.full_messages.each do |msg| %>
      <!-- displays 'Description can't be blank' -->
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<!-- this is the form for creating the new todo item or editing a current todo listing item -->
<%= form_for obj do |f| %>
  <p>
    <!-- sets 'Description' as the label -->
    <%= f.label :description %>
    <!-- text field for inputing your new todo item or edit it-->
    <%= f.text_field :description %>
  </p>
  <p>
    <!-- submits the form -->
    <!-- if the todo listing item is a new object then it will display 'Create New Todo' -->
    <!-- else it will display -->
    <%= f.submit(obj.new_record? ? "Create New Todo" : "Edit Todo") %>
  </p>
<% end %>

todo/app/views/listings/edit.html.erb
 <!-- /listings/:id/edit -->

<h1>Edit your Todo</h1>

<!-- uses the form partial -->
<%= render 'form', obj: @listing %>

todo/app/views/listings/index.html.erb
<!-- root(/) -->

<h1>Todo's</h1>

<!-- iterates over each listings item inorder to dispaly them in this ul -->
<% @listings.each do |listing| %>
  <ul>
    <!-- displays each todo list item in listings -->
    <!-- this todo list item also links to its own show path -->
    <li><%= link_to listing.description, listing_path(listing) %></li>
    <!-- this is a link to edit the current todo list item also passes its :id to the path -->
    <%= link_to "edit todo", edit_listing_path(listing) %> ||
    <!-- this is a link to delete the current todo listing item from the the todo list -->
    <!-- prompts the user if he/she really want to delete the listing item -->
    <%= link_to "[delete todo]", listing, method: :delete, data: { confirm: "Are you sure?" } %>
  </ul>
<% end %>

<!-- this links to the new todo page-->
<%= link_to "Creat a new todo", new_listing_path %>

todo/app/views/listings/new.html.erb
 <!-- /listings/new -->

<h1>Add a new Todo</h1>

<!-- uses the form partial -->
<%= render 'form', obj: @listing %>

todo/app/views/listings/show.html.erb
<!-- /listings/:id -->

<h1>View your todo</h1>

<!-- shows the current todo listing item -->
<p>
  <%= @listing.description %>
</p>
<!-- links to the edit todo page  -->
<p>
  <%= link_to "edit this todo", edit_listing_path(@listing) %>
</p>
<!-- links to the index(root) todo page  -->
<p>
  <%= link_to "back to your Todo's listing", listings_path %>
</p>